---
name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  setup-flux-envsubst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./setup-flux-envsubst
